version: '3.1'

services:
  reactapp:
    image: "dataspacesapp"
    restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - 8101:8101
    networks:
    - dataspacesnw  
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    
networks:
  dataspacesnw:
    external: true
