# Generated by Django 3.2.9 on 2021-12-30 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationMethod',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Datasource Name')),
                ('type', models.CharField(default='file', max_length=50, verbose_name='Datasource Type')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Dataset Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date/Time')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated Date/Time')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSetType',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Dataset Type Definition')),
            ],
        ),
        migrations.CreateModel(
            name='PersistenceComponent',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Datasource Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(default='file', max_length=50, verbose_name='Datasource Type')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=250, verbose_name='label')),
            ],
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Datasource Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('infoUrl', models.URLField(blank=True, null=True)),
                ('type', models.CharField(default='nfs', max_length=50, verbose_name='Datasource Type')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Datasource hostname')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Datasource path')),
                ('environment_id', models.CharField(max_length=36, null=True)),
                ('authentication_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.authenticationmethod', verbose_name='Authentication Method')),
                ('persistence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.persistencecomponent', verbose_name='Persistence Component')),
                ('tag', models.ManyToManyField(blank=True, related_name='datasources', to='api.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='DataSetUserRating',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=40)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DataSetTypeCharacteristic',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('dstc_name', models.CharField(max_length=250, verbose_name='Data Characteristic Name')),
                ('dstc_value', models.CharField(max_length=250, verbose_name='Data Characteristic Value')),
                ('c_dst_characteristic', models.ManyToManyField(related_name='_api_datasettypecharacteristic_c_dst_characteristic_+', to='api.DataSetTypeCharacteristic', verbose_name='Characteristic')),
                ('dstc_datasettype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='characteristics', to='api.datasettype', verbose_name='Data Set Type')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='datasource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_sets', to='api.datasource', verbose_name='Datasource'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='set_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_sets', to='api.datasettype', verbose_name='Datasource'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(related_name='data_sets', to='api.Tag'),
        ),
        migrations.CreateModel(
            name='DataCharacteristic',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=250, verbose_name='Data Characteristic Name')),
                ('c_value', models.CharField(max_length=250, verbose_name='Data Characteristic Value')),
                ('c_characteristic', models.ManyToManyField(related_name='_api_datacharacteristic_c_characteristic_+', to='api.DataCharacteristic', verbose_name='Characteristic')),
                ('c_dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='characteristics', to='api.dataset', verbose_name='Dataset')),
            ],
        ),
    ]
