# Generated by Django 3.2.9 on 2022-01-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datasource_typedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='host',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='path',
        ),
    ]
