# Generated by Django 3.2.9 on 2022-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220125_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='plugin_id',
            field=models.CharField(default='http', max_length=50, verbose_name='Datasource Plugin ID'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(default='http', max_length=50, verbose_name='Datasource Type'),
        ),
    ]
