# Generated by Django 3.2.9 on 2022-02-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220126_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='authentication_method',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='persistence',
        ),
        migrations.DeleteModel(
            name='AuthenticationMethod',
        ),
        migrations.DeleteModel(
            name='PersistenceComponent',
        ),
    ]
