# Generated by Django 3.2.9 on 2022-03-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dataset_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='size_type',
            field=models.CharField(blank=True, default='file', max_length=20, null=True, verbose_name='Size type'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='size',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Size'),
        ),
    ]
